l='K.r.i.s.h.n.a'
o='k.r.i.s.h.n.a'
j="krishna,gupta"
s="Krishna"
n='123'
m="lkj123"
h="h,h,h!,h$"
print(l.split())
print("- ".join(l))
print(l.isalpha())
print(n.isdigit())
print(m.isalnum())
print(l.upper())
print(l.title())
print(j.title())
print(s.istitle())
print(l.isprintable())
print(l.isprintable())
print(h.count("h!"))
print(h.find("$"))
print(m.replace("l","oo"))
print(o.capitalize())
print(j.capitalize())
print(s.capitalize())
print(s.endswith("nan"))
print(s.startswith("K"))
print("HEELO!@33".lower())
print("HEELO!@33".index("O"))
print("hElLon".swapcase())
print(s.split())